/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Listing {
  'id' : bigint,
  'totalRatings' : bigint,
  'city' : string,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'listingType' : { 'atm' : null } |
    { 'institution' : null } |
    { 'shop' : null },
  'state' : string,
  'address' : string,
  'openHours' : string,
  'category' : { 'retail' : null } |
    { 'healthcare' : null } |
    { 'finance' : null } |
    { 'other' : null } |
    { 'food' : null } |
    { 'education' : null } |
    { 'services' : null },
  'rating' : number,
  'phone' : string,
  'pincode' : string,
}
export interface ListingUpdateData {
  'city' : [] | [string],
  'name' : [] | [string],
  'description' : [] | [string],
  'isActive' : [] | [boolean],
  'listingType' : [] | [
    { 'atm' : null } |
      { 'institution' : null } |
      { 'shop' : null }
  ],
  'state' : [] | [string],
  'address' : [] | [string],
  'openHours' : [] | [string],
  'category' : [] | [
    { 'retail' : null } |
      { 'healthcare' : null } |
      { 'finance' : null } |
      { 'other' : null } |
      { 'food' : null } |
      { 'education' : null } |
      { 'services' : null }
  ],
  'phone' : [] | [string],
  'pincode' : [] | [string],
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createListing' : ActorMethod<
    [
      string,
      { 'atm' : null } |
        { 'institution' : null } |
        { 'shop' : null },
      { 'retail' : null } |
        { 'healthcare' : null } |
        { 'finance' : null } |
        { 'other' : null } |
        { 'food' : null } |
        { 'education' : null } |
        { 'services' : null },
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    bigint
  >,
  'deleteListing' : ActorMethod<[bigint], undefined>,
  'getAllActiveListings' : ActorMethod<[], Array<Listing>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getListing' : ActorMethod<[bigint], [] | [Listing]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rateListing' : ActorMethod<[bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchListings' : ActorMethod<
    [
      string,
      [] | [{ 'atm' : null } | { 'institution' : null } | { 'shop' : null }],
      [] | [
        { 'retail' : null } |
          { 'healthcare' : null } |
          { 'finance' : null } |
          { 'other' : null } |
          { 'food' : null } |
          { 'education' : null } |
          { 'services' : null }
      ],
      [] | [string],
    ],
    Array<Listing>
  >,
  'updateListing' : ActorMethod<[bigint, ListingUpdateData], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];