/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Listing = IDL.Record({
  'id' : IDL.Nat,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'totalRatings' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'listingType' : IDL.Variant({
    'atm' : IDL.Null,
    'institution' : IDL.Null,
    'shop' : IDL.Null,
  }),
  'state' : IDL.Text,
  'address' : IDL.Text,
  'openHours' : IDL.Text,
  'category' : IDL.Variant({
    'retail' : IDL.Null,
    'healthcare' : IDL.Null,
    'finance' : IDL.Null,
    'other' : IDL.Null,
    'food' : IDL.Null,
    'education' : IDL.Null,
    'services' : IDL.Null,
  }),
  'rating' : IDL.Float64,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ListingUpdateData = IDL.Record({
  'lat' : IDL.Opt(IDL.Float64),
  'lng' : IDL.Opt(IDL.Float64),
  'city' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Opt(IDL.Bool),
  'listingType' : IDL.Opt(
    IDL.Variant({
      'atm' : IDL.Null,
      'institution' : IDL.Null,
      'shop' : IDL.Null,
    })
  ),
  'state' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'openHours' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(
    IDL.Variant({
      'retail' : IDL.Null,
      'healthcare' : IDL.Null,
      'finance' : IDL.Null,
      'other' : IDL.Null,
      'food' : IDL.Null,
      'education' : IDL.Null,
      'services' : IDL.Null,
    })
  ),
  'phone' : IDL.Opt(IDL.Text),
  'pincode' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({
          'atm' : IDL.Null,
          'institution' : IDL.Null,
          'shop' : IDL.Null,
        }),
        IDL.Variant({
          'retail' : IDL.Null,
          'healthcare' : IDL.Null,
          'finance' : IDL.Null,
          'other' : IDL.Null,
          'food' : IDL.Null,
          'education' : IDL.Null,
          'services' : IDL.Null,
        }),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteListing' : IDL.Func([IDL.Nat], [], []),
  'getAllActiveListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getListing' : IDL.Func([IDL.Nat], [IDL.Opt(Listing)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rateListing' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchListings' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(
          IDL.Variant({
            'atm' : IDL.Null,
            'institution' : IDL.Null,
            'shop' : IDL.Null,
          })
        ),
        IDL.Opt(
          IDL.Variant({
            'retail' : IDL.Null,
            'healthcare' : IDL.Null,
            'finance' : IDL.Null,
            'other' : IDL.Null,
            'food' : IDL.Null,
            'education' : IDL.Null,
            'services' : IDL.Null,
          })
        ),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Vec(Listing)],
      ['query'],
    ),
  'updateListing' : IDL.Func([IDL.Nat, ListingUpdateData], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Listing = IDL.Record({
    'id' : IDL.Nat,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'totalRatings' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'listingType' : IDL.Variant({
      'atm' : IDL.Null,
      'institution' : IDL.Null,
      'shop' : IDL.Null,
    }),
    'state' : IDL.Text,
    'address' : IDL.Text,
    'openHours' : IDL.Text,
    'category' : IDL.Variant({
      'retail' : IDL.Null,
      'healthcare' : IDL.Null,
      'finance' : IDL.Null,
      'other' : IDL.Null,
      'food' : IDL.Null,
      'education' : IDL.Null,
      'services' : IDL.Null,
    }),
    'rating' : IDL.Float64,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ListingUpdateData = IDL.Record({
    'lat' : IDL.Opt(IDL.Float64),
    'lng' : IDL.Opt(IDL.Float64),
    'city' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Opt(IDL.Bool),
    'listingType' : IDL.Opt(
      IDL.Variant({
        'atm' : IDL.Null,
        'institution' : IDL.Null,
        'shop' : IDL.Null,
      })
    ),
    'state' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'openHours' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(
      IDL.Variant({
        'retail' : IDL.Null,
        'healthcare' : IDL.Null,
        'finance' : IDL.Null,
        'other' : IDL.Null,
        'food' : IDL.Null,
        'education' : IDL.Null,
        'services' : IDL.Null,
      })
    ),
    'phone' : IDL.Opt(IDL.Text),
    'pincode' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({
            'atm' : IDL.Null,
            'institution' : IDL.Null,
            'shop' : IDL.Null,
          }),
          IDL.Variant({
            'retail' : IDL.Null,
            'healthcare' : IDL.Null,
            'finance' : IDL.Null,
            'other' : IDL.Null,
            'food' : IDL.Null,
            'education' : IDL.Null,
            'services' : IDL.Null,
          }),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteListing' : IDL.Func([IDL.Nat], [], []),
    'getAllActiveListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getListing' : IDL.Func([IDL.Nat], [IDL.Opt(Listing)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rateListing' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchListings' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(
            IDL.Variant({
              'atm' : IDL.Null,
              'institution' : IDL.Null,
              'shop' : IDL.Null,
            })
          ),
          IDL.Opt(
            IDL.Variant({
              'retail' : IDL.Null,
              'healthcare' : IDL.Null,
              'finance' : IDL.Null,
              'other' : IDL.Null,
              'food' : IDL.Null,
              'education' : IDL.Null,
              'services' : IDL.Null,
            })
          ),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Vec(Listing)],
        ['query'],
      ),
    'updateListing' : IDL.Func([IDL.Nat, ListingUpdateData], [], []),
  });
};

export const init = ({ IDL }) => { return []; };