/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Listing {
    id: bigint;
    totalRatings: bigint;
    city: string;
    name: string;
    description: string;
    isActive: boolean;
    listingType: Variant_atm_institution_shop;
    state: string;
    address: string;
    openHours: string;
    category: Variant_retail_healthcare_finance_other_food_education_services;
    rating: number;
    phone: string;
    pincode: string;
}
export interface UserProfile {
    name: string;
}
export interface ListingUpdateData {
    city?: string;
    name?: string;
    description?: string;
    isActive?: boolean;
    listingType?: Variant_atm_institution_shop;
    state?: string;
    address?: string;
    openHours?: string;
    category?: Variant_retail_healthcare_finance_other_food_education_services;
    phone?: string;
    pincode?: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_atm_institution_shop {
    atm = "atm",
    institution = "institution",
    shop = "shop"
}
export enum Variant_retail_healthcare_finance_other_food_education_services {
    retail = "retail",
    healthcare = "healthcare",
    finance = "finance",
    other = "other",
    food = "food",
    education = "education",
    services = "services"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createListing(name: string, listingType: Variant_atm_institution_shop, category: Variant_retail_healthcare_finance_other_food_education_services, address: string, city: string, state: string, pincode: string, phone: string, description: string, openHours: string): Promise<bigint>;
    deleteListing(id: bigint): Promise<void>;
    getAllActiveListings(): Promise<Array<Listing>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getListing(id: bigint): Promise<Listing | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    rateListing(listingId: bigint, rating: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchListings(keyword: string, listingTypeFilter: Variant_atm_institution_shop | null, categoryFilter: Variant_retail_healthcare_finance_other_food_education_services | null, cityFilter: string | null): Promise<Array<Listing>>;
    updateListing(id: bigint, updateData: ListingUpdateData): Promise<void>;
}
import type { Listing as _Listing, ListingUpdateData as _ListingUpdateData, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createListing(arg0: string, arg1: Variant_atm_institution_shop, arg2: Variant_retail_healthcare_finance_other_food_education_services, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(arg0, to_candid_variant_n3(this._uploadFile, this._downloadFile, arg1), to_candid_variant_n4(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(arg0, to_candid_variant_n3(this._uploadFile, this._downloadFile, arg1), to_candid_variant_n4(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async deleteListing(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteListing(arg0);
            return result;
        }
    }
    async getAllActiveListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveListings();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveListings();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListing(arg0: bigint): Promise<Listing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getListing(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListing(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async rateListing(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rateListing(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rateListing(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchListings(arg0: string, arg1: Variant_atm_institution_shop | null, arg2: Variant_retail_healthcare_finance_other_food_education_services | null, arg3: string | null): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchListings(arg0, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg3));
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchListings(arg0, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg3));
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateListing(arg0: bigint, arg1: ListingUpdateData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateListing(arg0, to_candid_ListingUpdateData_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateListing(arg0, to_candid_ListingUpdateData_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Listing_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Listing): Listing {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Listing]): Listing | null {
    return value.length === 0 ? null : from_candid_Listing_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    totalRatings: bigint;
    city: string;
    name: string;
    description: string;
    isActive: boolean;
    listingType: {
        atm: null;
    } | {
        institution: null;
    } | {
        shop: null;
    };
    state: string;
    address: string;
    openHours: string;
    category: {
        retail: null;
    } | {
        healthcare: null;
    } | {
        finance: null;
    } | {
        other: null;
    } | {
        food: null;
    } | {
        education: null;
    } | {
        services: null;
    };
    rating: number;
    phone: string;
    pincode: string;
}): {
    id: bigint;
    totalRatings: bigint;
    city: string;
    name: string;
    description: string;
    isActive: boolean;
    listingType: Variant_atm_institution_shop;
    state: string;
    address: string;
    openHours: string;
    category: Variant_retail_healthcare_finance_other_food_education_services;
    rating: number;
    phone: string;
    pincode: string;
} {
    return {
        id: value.id,
        totalRatings: value.totalRatings,
        city: value.city,
        name: value.name,
        description: value.description,
        isActive: value.isActive,
        listingType: from_candid_variant_n8(_uploadFile, _downloadFile, value.listingType),
        state: value.state,
        address: value.address,
        openHours: value.openHours,
        category: from_candid_variant_n9(_uploadFile, _downloadFile, value.category),
        rating: value.rating,
        phone: value.phone,
        pincode: value.pincode
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    atm: null;
} | {
    institution: null;
} | {
    shop: null;
}): Variant_atm_institution_shop {
    return "atm" in value ? Variant_atm_institution_shop.atm : "institution" in value ? Variant_atm_institution_shop.institution : "shop" in value ? Variant_atm_institution_shop.shop : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    retail: null;
} | {
    healthcare: null;
} | {
    finance: null;
} | {
    other: null;
} | {
    food: null;
} | {
    education: null;
} | {
    services: null;
}): Variant_retail_healthcare_finance_other_food_education_services {
    return "retail" in value ? Variant_retail_healthcare_finance_other_food_education_services.retail : "healthcare" in value ? Variant_retail_healthcare_finance_other_food_education_services.healthcare : "finance" in value ? Variant_retail_healthcare_finance_other_food_education_services.finance : "other" in value ? Variant_retail_healthcare_finance_other_food_education_services.other : "food" in value ? Variant_retail_healthcare_finance_other_food_education_services.food : "education" in value ? Variant_retail_healthcare_finance_other_food_education_services.education : "services" in value ? Variant_retail_healthcare_finance_other_food_education_services.services : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Listing>): Array<Listing> {
    return value.map((x)=>from_candid_Listing_n6(_uploadFile, _downloadFile, x));
}
function to_candid_ListingUpdateData_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingUpdateData): _ListingUpdateData {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_atm_institution_shop | null): [] | [{
        atm: null;
    } | {
        institution: null;
    } | {
        shop: null;
    }] {
    return value === null ? candid_none() : candid_some(to_candid_variant_n3(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_retail_healthcare_finance_other_food_education_services | null): [] | [{
        retail: null;
    } | {
        healthcare: null;
    } | {
        finance: null;
    } | {
        other: null;
    } | {
        food: null;
    } | {
        education: null;
    } | {
        services: null;
    }] {
    return value === null ? candid_none() : candid_some(to_candid_variant_n4(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    city?: string;
    name?: string;
    description?: string;
    isActive?: boolean;
    listingType?: Variant_atm_institution_shop;
    state?: string;
    address?: string;
    openHours?: string;
    category?: Variant_retail_healthcare_finance_other_food_education_services;
    phone?: string;
    pincode?: string;
}): {
    city: [] | [string];
    name: [] | [string];
    description: [] | [string];
    isActive: [] | [boolean];
    listingType: [] | [{
            atm: null;
        } | {
            institution: null;
        } | {
            shop: null;
        }];
    state: [] | [string];
    address: [] | [string];
    openHours: [] | [string];
    category: [] | [{
            retail: null;
        } | {
            healthcare: null;
        } | {
            finance: null;
        } | {
            other: null;
        } | {
            food: null;
        } | {
            education: null;
        } | {
            services: null;
        }];
    phone: [] | [string];
    pincode: [] | [string];
} {
    return {
        city: value.city ? candid_some(value.city) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none(),
        isActive: value.isActive ? candid_some(value.isActive) : candid_none(),
        listingType: value.listingType ? candid_some(to_candid_variant_n3(_uploadFile, _downloadFile, value.listingType)) : candid_none(),
        state: value.state ? candid_some(value.state) : candid_none(),
        address: value.address ? candid_some(value.address) : candid_none(),
        openHours: value.openHours ? candid_some(value.openHours) : candid_none(),
        category: value.category ? candid_some(to_candid_variant_n4(_uploadFile, _downloadFile, value.category)) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none(),
        pincode: value.pincode ? candid_some(value.pincode) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_atm_institution_shop): {
    atm: null;
} | {
    institution: null;
} | {
    shop: null;
} {
    return value == Variant_atm_institution_shop.atm ? {
        atm: null
    } : value == Variant_atm_institution_shop.institution ? {
        institution: null
    } : value == Variant_atm_institution_shop.shop ? {
        shop: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_retail_healthcare_finance_other_food_education_services): {
    retail: null;
} | {
    healthcare: null;
} | {
    finance: null;
} | {
    other: null;
} | {
    food: null;
} | {
    education: null;
} | {
    services: null;
} {
    return value == Variant_retail_healthcare_finance_other_food_education_services.retail ? {
        retail: null
    } : value == Variant_retail_healthcare_finance_other_food_education_services.healthcare ? {
        healthcare: null
    } : value == Variant_retail_healthcare_finance_other_food_education_services.finance ? {
        finance: null
    } : value == Variant_retail_healthcare_finance_other_food_education_services.other ? {
        other: null
    } : value == Variant_retail_healthcare_finance_other_food_education_services.food ? {
        food: null
    } : value == Variant_retail_healthcare_finance_other_food_education_services.education ? {
        education: null
    } : value == Variant_retail_healthcare_finance_other_food_education_services.services ? {
        services: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
